#ifndef EXERCICIOS
#define EXERCICIOS
#include "../arvores/arvores.hpp"
void exercicio1a();
void exercicio1b();
void exercicio1c();
void exercicio1d();
void exercicio1e();
void exercicio1f();
void exercicio1g();
void exercicio1h();
void exercicio2();
void exercicio3();
void exercicio4();
void exercicio5();
void exercicio6();
void exercicio7();
void exercicio8();
void exercicio9();
void exercicio10();
void exercicio11();
void exercicio12();
#endif